#!/usr/bin/env sh
set -eu

echo "Checking formatting..."
if ! cargo fmt --check; then
  echo "❌ Formatting issues found. Run 'cargo fmt' and try again."
  exit 1
fi

# echo "Running cargo clippy..."
# cargo clippy --all-features -- -D warnings
