/* use std::arch::global_asm;
use std::collections::HashMap;
use std::f32::consts::E; */

use crate::utils::bow::*;
use crate::utils::fs::*;
use crate::utils::regex::*;
use crate::utils::{/* csv::*,  */ logger::Logger};
use anyhow::{/*anyhow, bail, Context,  */ Result};
use tracing::info;
/* use clang::token;
use polars::frame::row; */
use clap::{Arg, /* ArgAction, */ Command};
use polars::prelude::*;
//use std::collections::HashMap;
/* struct Token {
    word: Vec<u8>,
    local_count: usize,
    global_count: usize,
    global_position: usize,
} */

pub fn cli() -> Command {
    Command::new("tokenizer")
        .about("Tokenizes the functions in the input file and generates a global Bag of Words.")
        .disable_version_flag(true)
        .arg(
            Arg::new("input")
                .short('i')
                .long("input")
                .value_name("INPUT_PATH")
                .help("Path to the input CSV file generated by the parser.")
                .required(true),
        )
        .arg(
            Arg::new("example_word")
                .short('e')
                .long("example-word")
                .value_name("EXAMPLE_WORD")
                .help("An example word to check the global Bag of Words for.")
                .required(false),
        )
}

pub fn run(input_path: &str, example_word: &str, _logger: &Logger) -> Result<()> {
    let language = "java";
    let minimum_loc = 5;

    let mut input_file = open_csv(
        input_path,
        Some(Schema::from_iter(vec![
            Field::new("id".into(), DataType::UInt32),
            Field::new("path".into(), DataType::String),
            Field::new("name".into(), DataType::String),
            Field::new("position".into(), DataType::String),
            Field::new("loc".into(), DataType::UInt32),
            Field::new("words".into(), DataType::UInt32),
        ])),
        Some(vec![
            "id", "path", "name", "position", "language", "loc", "words",
        ]),
    )?;

    let n_functions_before_language = input_file.height();
    info!(
        "{} functions found in the input file, filtering by selected language",
        n_functions_before_language
    );

    input_file = input_file
        .lazy()
        .filter(col("language").eq(lit(language)))
        .collect()?;

    let n_functions_after_language = input_file.height();
    info!(
        "  {} files found after filtering ({:.2} %)",
        n_functions_after_language,
        if n_functions_before_language == 0 {
            0
        } else {
            n_functions_after_language / n_functions_before_language * 100
        }
    );
    let n_functions_before_loc = input_file.height();

    info!(" {} functions found after filtering by language, filtering functions with less that {} lines of code.", n_functions_before_loc, minimum_loc);

    //input_file = input_file.filter(&input_file.column("loc")?.greater_equal(minimum_loc))?;

    input_file = input_file
        .lazy()
        .filter(col("loc").gt_eq(lit(minimum_loc)))
        .collect()?;

    let n_functions_after_loc = input_file.height();

    info!(
        "{} functions found after filtering  ({:.2} %)", //something is weird with the percentage calculation here.
        n_functions_after_loc,
        if n_functions_before_loc == 0 {
            0
        } else {
            n_functions_after_loc / n_functions_before_loc * 100
        }
    );

    //let token_rankings = run_tokenizer(&input_file, logger)?;
    let token_rankings = global_counter(&input_file)?.token_rankings();
    let example_word = example_word.to_ascii_lowercase();
    let example_word_token = example_word.as_bytes();

    info!(
        "Global Bag of Words generated. Checking for example word '{}'",
        example_word
    );
    info!(
        "  The token '{}' appears {} times and is ranked {} in the global Bag of Words (rank 1 = least common token).",
        example_word,
        token_rankings
            .get(example_word_token)
            .unwrap_or(&0),
        token_rankings
            .get(example_word_token)
            .unwrap_or(&0)
    );

    Ok(())
}

pub fn global_counter(input_file: &DataFrame) -> Result<Bow> {
    info!("Building global Bag of Words from the functions in the input file...");
    let paths_column = input_file.column("path").and_then(|c| c.str())?;

    let word_matcher: Matcher = Matcher::words_matcher();
    let mut global_bow: Bow = Bow::new(true);

    for row in paths_column.into_iter() {
        match row {
            Some(path) => {
                //let function_code = std::fs::read_to_string(path)?;
                match load_file(path, 1024 * 1024 * 1024) {
                    Ok(Ok(function_code)) => {
                        let local_bow = word_matcher.bag_of_words(&function_code, true);
                        global_bow.extend(local_bow);
                    }
                    Ok(Err(_e)) => {
                        info!("  Warning: File too large at path {}", path);
                    }
                    Err(_e) => {
                        info!("  Warning: Could not load file at path {}", path);
                    }
                }
            }
            None => {
                info!("  Warning: Path not found");
            }
        }
    }
    Ok(global_bow)
}
