use crate::phases::tokenizer::global_counter;
use crate::utils::candidate_map::*;
use crate::utils::fs::*;
use crate::utils::inverted_index::*;
use crate::utils::logger::{log_output_file, log_write_dataframe, Logger};
use crate::utils::regex::*;
use anyhow::Context;
use anyhow::{/* Error,  */ Result};
use clap::ArgAction;
use clap::{Arg, Command};
use core::f64;
use either::Either;
use indicatif::ProgressBar;
use polars::prelude::*;
use std::cmp::{max, min};
use std::collections::{HashMap, HashSet};
use std::vec;
use tracing::{debug, info, warn};

type CloneMap<'a> = HashMap<&'a str, Either<HashSet<&'a str>, &'a str>>;
type Word = Vec<u8>;

pub fn cli() -> Command {
    Command::new("type_3_duplicate_files")
        .about("Detects type 3 clones by building an index based on the most common tokens in the functions and their frequencies.")
        .disable_version_flag(true)
        .arg(
            Arg::new("input")
                .short('i')
                .long("input")
                .help("Path to the input CSV file generated by the parser.")
                .required(true),
        )
        .arg(
            Arg::new("output")
                .short('o')
                .long("output")
                .help("Path to the output CSV file to store unique files metadata.")
                .required(false),
        )
        .arg(
            Arg::new("map")
                .short('m')
                .long("map")
                .help("Path to the map CSV file to store the mapping of clones to their originals.")
                .required(false),
        )
        .arg(
            Arg::new("logs")
                .short('l')
                .long("logs")
                .help("Path to the logs file to store error logs.")
                .required(false),
        )
        .arg(
            Arg::new("language")
                .short('g')
                .long("languages")
                /* .help("Comma-separated list of languages to consider. If not provided, all languages will be considered.") */
                .help("language as a string, e.g. 'java'. If not provided, defaults to 'java'. TODO")
                .required(false),
        )
        .arg(
            Arg::new("threads")
                .short('n')
                .help("Number of threads to use, default is 1.  CURRENT VERSION IS SINGLE THREADED")
                .default_value("1")
                .value_parser(clap::value_parser!(usize))
        )
        .arg(
            Arg::new("p_prefix")
                .short('p')
                .long("p_prefix")
                .default_value("1")
                .help("Number of tokens to consider for the prefix. Default is 1.")
                .value_parser(clap::value_parser!(usize))
        )
        .arg(
            Arg::new("threshold")
                .short('t')
                .long("threshold")
                .help("Similarity threshold. Default is 0.8.")
                .default_value("0.8")
                .value_parser(clap::value_parser!(f64))
        )
        .arg(
            Arg::new("example_word")
                .short('e')
                .long("example-word")
                .help("An example word to check the global Bag of Words for.")
                .required(false),
        )
        .arg(
            Arg::new("force")
                .short('f')
                .long("force")
                .help("Override the output CSV file if it already exists.")
                .default_value("false")
                .action(ArgAction::SetTrue)
        )
        .arg(
            Arg::new("header")
                .long("header")
                .help("Name of column storing file paths in the input CSV file.")
                .default_value("path"),
        )
}

pub fn run(
    input_path: &str, //The path to the input CSV file storing the file paths, output of the parser phase
    _output_path: Option<&str>, //optional path to the output CSV file to store unique files metadata.
    _map_path: Option<&str>, //optional path to the map CSV file to store the mapping of clones to their originals.
    _logs_path: Option<&str>, //for error logs, not implemented yet
    /* _opt_languages: Option<Vec<&str>>, //optional list of languages. Currently java is hardcoded */
    opt_language: Option<&str>,
    _threads: usize,    //current implementation is single-threaded
    p_prefix: usize,    //number of tokens to consider for the prefix, default is 1
    threshold: f64,     //threshold for the prefix length, default is 0.8
    force: bool,        //whether to override the output CSV file if it already exists
    input_header: &str, //name of column storing file paths in the input CSV file
    _logger: &Logger,
) -> Result<()> {
    let language = opt_language.unwrap_or("java"); //default to java currently
    let minimum_loc = 0; //temporary
    let mut input_file = open_csv(
        input_path,
        Some(Schema::from_iter(vec![
            Field::new("id".into(), DataType::UInt32),
            Field::new("path".into(), DataType::String),
            Field::new("name".into(), DataType::String),
            Field::new("position".into(), DataType::String),
            Field::new("loc".into(), DataType::UInt32),
            Field::new("words".into(), DataType::UInt32),
        ])),
        Some(vec![
            "id", "path", "name", "position", "language", "loc", "words",
        ]),
    )?;

    let n_functions_before_language = input_file.height();
    info!(
        "{} functions found in the input file, filtering by selected language",
        n_functions_before_language
    );

    //input_file = input_file.filter(&input_file.column("language")?.equal(language));
    input_file = input_file
        .lazy()
        .filter(col("language").eq(lit(language)))
        .collect()?;

    let n_functions_after_language = input_file.height();
    info!(
        "  {} files found after filtering ({:.2} %)",
        n_functions_after_language,
        if n_functions_before_language == 0 {
            0
        } else {
            (n_functions_after_language as f64 / n_functions_before_language as f64 * 100.0)
                as usize
        }
    );
    let n_functions_before_loc = input_file.height();

    info!(" {} functions found after filtering by language, filtering functions with less that {} lines of code.", n_functions_before_loc, minimum_loc);

    input_file = input_file
        .lazy()
        .filter(col("loc").gt_eq(lit(minimum_loc)))
        .collect()?;

    let n_functions_after_loc = input_file.height();

    //moved here from detect_clones
    let paths_column = input_file.column(input_header)?.str()?;
    let words_column = input_file.column("words")?.u32()?;
    let rows: HashMap<&str, usize> = paths_column
        .into_iter()
        .zip(words_column)
        .filter_map(|(path_opt, words_opt)| match (path_opt, words_opt) {
            (Some(path), Some(words)) => Some((path, words as usize)),
            _ => None,
        })
        .collect();

    let token_rankings: HashMap<Vec<u8>, usize> = global_counter(&input_file)?.token_rankings();
    let (vector_of_indices, min_words, max_words) =
        index_builder(&input_file, &token_rankings, p_prefix, threshold, &rows)?;
    // Maximum and minimum 'words' in input file
    info!(
        "Built {} indices with prefix scheme from 1 to {}, minimum words in a function: {}, maximum words in a function: {}.",
        vector_of_indices.len(),
        p_prefix,
        min_words,
        max_words
    );

    // if let Some(word) = example_word {
    //     let word = word.to_owned().as_bytes().to_ascii_lowercase();
    //     let mut index_number = 1;
    //     for index in vector_of_indices.iter() {
    //         debug!(
    //             "Index {} has {} entries, total length of vectors in entries: {}",
    //             index_number,
    //             index.len(),
    //             index.len_tokens()
    //         );
    //         if let Some(entries) = index.get(&word) {
    //             debug!(
    //                 "Entries for the example word '{}' in index {}§:",
    //                 String::from_utf8_lossy(&word),
    //                 index_number
    //             );
    //             for (function_id, count, (token_position, cumulative_count)) in entries {
    //                 debug!(
    //                     "Function ID: {}, Count: {}, Token Position: {}, Cumulative Count: {}",
    //                     function_id, count, token_position, cumulative_count
    //                 );
    //             }
    //         } else {
    //             debug!(
    //                 "The example word '{}' was not found in index {}.",
    //                 String::from_utf8_lossy(&word),
    //                 index_number
    //             );
    //         }
    //         index_number += 1;
    //     }
    // }

    //go through input file again? Means i can grab 'words' from the file. Could do something like just checking candidates
    let clone_map = detect_clones(&token_rankings, &vector_of_indices, threshold, &rows)?;

    // Ok() is kept at the end of the function
    // Prepare CSV outputs: map of clone -> origin, and unique files list
    let default_output_path: String = format!("{input_path}.unique.csv");
    let default_map_path: String = format!("{input_path}.duplicates_map.csv");
    let output_path: &str = _output_path.unwrap_or(&default_output_path);
    let map_path: &str = _map_path.unwrap_or(&default_map_path);

    // Build clone -> origin mapping
    let mut clone_to_origin: HashMap<&str, &str> = HashMap::new();
    for (k, v) in clone_map {
        match v {
            Either::Left(set) => {
                for c in set {
                    clone_to_origin.insert(c, k);
                }
            }
            Either::Right(origin) => {
                clone_to_origin.insert(k, origin);
            }
        }
    }

    let clone_to_origin = clone_to_origin; //make immutable

    // Map CSV rows
    let mut map_names: Vec<&str> = Vec::new();
    let mut map_originals: Vec<&str> = Vec::new();
    for (clone_path, origin_path) in &clone_to_origin {
        map_names.push(clone_path);
        map_originals.push(origin_path);
    }

    let mut map_df = DataFrame::new(vec![
        polars::prelude::Column::new("name".into(), map_names),
        polars::prelude::Column::new("original".into(), map_originals),
    ])?;

    // Unique files: those that are not listed as clones
    let mut unique_paths: Vec<&str> = Vec::new();
    let mut unique_words: Vec<u32> = Vec::new();
    for (path, words) in rows {
        if !clone_to_origin.contains_key(path) {
            unique_paths.push(path);
            unique_words.push(words as u32);
        }
    }

    let mut output_df = DataFrame::new(vec![
        polars::prelude::Column::new("path".into(), unique_paths),
        polars::prelude::Column::new("words".into(), unique_words),
    ])?;

    // Check output files and write
    log_output_file(output_path, false, force)?;
    log_write_dataframe(_logger, map_path, &mut map_df)?;
    log_write_dataframe(_logger, output_path, &mut output_df)?;

    info!(
        "Remaining files: {} / {:.2} %", //something is weird with the percentage calculation here.
        n_functions_after_loc,
        if n_functions_before_loc == 0 {
            0
        } else {
            (n_functions_after_loc as f64 / n_functions_before_loc as f64 * 100.0) as usize
        }
    );

    let unique_files = output_df.height();
    let unique_file_percentage = (unique_files as f64 / n_functions_after_loc as f64) * 100.0;

    info!(
        "Unique files: {} / {:.2} %",
        unique_files, unique_file_percentage
    );

    let duplicate_files = n_functions_after_loc - unique_files;
    let duplicate_file_percentage = (duplicate_files as f64 / n_functions_after_loc as f64) * 100.0;

    info!(
        "Duplicate files: {} / {:.2} %",
        duplicate_files, duplicate_file_percentage
    );

    Ok(())
}

fn prefix_length(word_count: usize, threshold: f64) -> usize {
    word_count - ((word_count as f64) * threshold).ceil() as usize + 1
}

fn index_builder<'a>(
    input_file: &'a DataFrame,
    token_rankings: &HashMap<Word, usize>,
    p_prefix: usize,
    threshold: f64,
    functions_lengths: &HashMap<&'a str, usize>,
) -> Result<(Vec<InvertedIndex<'a>>, usize, usize)> {
    info!("Building indices...");

    let mut vector_of_indices: Vec<InvertedIndex<'a>> =
        (0..p_prefix).map(|_| InvertedIndex::new()).collect();
    let mut min_words = usize::MAX;
    let mut max_words = 0;
    let paths = input_file.column("path")?.str()?.into_iter().flatten();
    for path in paths {
        let function_code = load_file(path, 1024 * 1024 * 1024)?
            .map_err(|e| anyhow::anyhow!("Error loading file '{}': {}.", path, e))?;
        let vector_bow = Matcher::words_matcher()
            .bag_of_words(&function_code, true)
            .sort_by(token_rankings)?;
        let codeblock_length: usize = functions_lengths
            .get(path)
            .copied()
            .with_context(|| format!("No entry found in functions_lengths for path '{}'.", path))?;
        min_words = min_words.min(codeblock_length);
        max_words = max_words.max(codeblock_length);
        let prefix_length: usize = prefix_length(codeblock_length, threshold);

        let mut cumulative_count = 0;
        let mut p = 0;

        for (idx, (token, count)) in vector_bow.into_iter().enumerate() {
            cumulative_count += count;
            vector_of_indices[p].add(&token, path, count, idx, cumulative_count);
            if cumulative_count >= prefix_length {
                p += 1;
                if p == p_prefix {
                    break;
                }
            }
        }
    }
    info!("Finished building indices.");
    Ok((vector_of_indices, min_words, max_words))
}

fn delta_filter_cost(
    token_tuple: &(Vec<u8>, usize),
    vector_of_indices: &[InvertedIndex],
    p_prefix: usize,
    new: bool,
) -> usize {
    let token = &token_tuple.0;
    let mut cost = 0;
    if new {
        //if the token is new to the prefix, we need to count its frequency in all previous delta indices
        for p in 1..=p_prefix {
            cost += vector_of_indices[p - 1].token_frequency(token, false);
        }
    } else {
        //just count the frequency in the new delta index
        cost += vector_of_indices[p_prefix - 1].token_frequency(token, false);
    }
    cost
}

fn weighted_prefix_end(vectored_bow: &[(Vec<u8>, usize)], prefix_length: usize) -> Result<usize> {
    let mut cumulative_count: usize = 0;
    for (idx, (_, count)) in vectored_bow.iter().enumerate() {
        cumulative_count += *count;
        if cumulative_count >= prefix_length {
            return Ok(idx + 1); //Enumerator is 0-based, so we need to add 1 to get the correct length of the prefix vector
        }
    }
    anyhow::bail!(
        "Unreachable: Prefix length {} is greater than the total number of tokens in the function ({}).",
        prefix_length,
        cumulative_count
    )
}

fn detect_clones<'a>(
    token_rankings: &HashMap<Word, usize>,
    vector_of_indices: &'a [InvertedIndex],
    threshold: f64,
    function_lengths: &HashMap<&'a str, usize>,
) -> Result<CloneMap<'a>> {
    // result will probably be a 'clone-map'. Unsure for now if it has to be its own data-structure or if i can reuse the candidate map from before.
    let mut clone_map: CloneMap = HashMap::new();

    let word_matcher: Matcher = Matcher::words_matcher();
    let p_prefix = vector_of_indices.len();
    info!("Detecting clones");
    let detection_progress = ProgressBar::new(function_lengths.len() as u64);
    detection_progress.set_style(
        indicatif::ProgressStyle::default_bar().template("{elapsed} {wide_bar} {percent}%")?,
    );

    for (path, origin_word_count) in function_lengths {
        debug!("-----------------------------------------------------------------------------");
        detection_progress.inc(1);
        // info!("Path: {}, Words: {}", path, origin_word_count);
        match load_file(path, 1024 * 1024 * 1024) {
            Ok(Ok(function_code)) => {
                let origin_vectored_bow = word_matcher
                    .bag_of_words(&function_code, true)
                    .sort_by(token_rankings)?;
                let mut candidate_map = CandidateMap::new();

                let init_prefix_end = weighted_prefix_end(
                    &origin_vectored_bow,
                    prefix_length(*origin_word_count, threshold),
                )?;
                let mut filter_cost_vector: Vec<usize> = Vec::new();
                filter_cost_vector.push(0); //cost of prefix scheme 1 is calculated from an empty prefix, so the initial cost is 0
                let mut verification_cost_vector: Vec<usize> = Vec::new();
                verification_cost_vector.push(0); //verification cost is estimated as 0 for the first prefix scheme since we haven't seen any candidates yet,
                let mut total_cost_vector: Vec<usize> = Vec::new();
                total_cost_vector.push(usize::MAX); //total cost is initially set to max since so 0-prefix can never be chosen as the best prefix scheme
                                                    // big loop, will be used for the different prefix schemes
                let mut origin_cumulative_count = 0usize;
                let mut origin_token_position = 0usize;
                'prefix_schemes: for p in 1..=p_prefix {
                    let mut filter_cost = filter_cost_vector[p - 1]; // start with the filter cost of the previous prefix scheme
                    let prefix_end = init_prefix_end + p - 1; //the prefix end for the current scheme is at least the prefix end of the first scheme + the number of tokens in the prefix - 1 (since p-prefix is at least 1)

                    while origin_token_position < prefix_end
                        && origin_token_position < origin_vectored_bow.len()
                    {
                        let token_tuple = origin_vectored_bow.get(origin_token_position).unwrap();
                        let is_new = origin_token_position + 1 == prefix_end;
                        origin_cumulative_count += token_tuple.1;
                        filter_cost += delta_filter_cost(token_tuple, vector_of_indices, p, is_new);
                        debug!(
                            "Origin {}, count {}, token {}, index {}, tok_pos {}, wordpos {}.",
                            path,
                            token_tuple.1,
                            String::from_utf8_lossy(&token_tuple.0),
                            p,
                            origin_token_position,
                            origin_cumulative_count
                        );
                        for candidate in vector_of_indices[p - 1]
                            .get(&token_tuple.0)
                            .unwrap_or(&Vec::new())
                        {
                            debug!("Candidate ID {}, count {}, token {}, index {}, tok_pos {}, wordpos {}.", candidate.0, candidate.1, String::from_utf8_lossy(&token_tuple.0), p, candidate.2, candidate.3);
                            if clone_map.contains_key(&candidate.0) {
                                debug!("DClone: SKIPPING candidate at path '{}' since it already has an entry in clone_map.", candidate.0);
                                continue;
                            }
                            let candidate_word_count =
                                function_lengths.get(&candidate.0).copied().unwrap_or(0);

                            if candidate_word_count
                                < ((*origin_word_count as f64) * threshold).round() as usize
                            {
                                debug!("DClone: SKIPPING candidate at path '{}' since its word count {} is below the threshold for clones with the origin ({} words, threshold {}).", candidate.0, candidate_word_count, origin_word_count, threshold);
                                continue; //skip candidates that are too small to reach the threshold
                            }

                            let new_matches = min(token_tuple.1, candidate.1);
                            let function = candidate.0;
                            let last_token_seen_pos = candidate.2;
                            let last_token_seen_cumul_count = candidate.3;
                            let current_threshold =
                                (max(*origin_word_count, candidate_word_count) as f64 * threshold)
                                    .round() as usize;
                            let upper_bound = min(
                                *origin_word_count - origin_cumulative_count,
                                candidate_word_count - last_token_seen_cumul_count,
                            );
                            if candidate_map.get_token_matches(function) + upper_bound + new_matches
                                >= current_threshold
                            {
                                candidate_map.add_pending_update(
                                    function,
                                    new_matches,
                                    last_token_seen_pos,
                                    last_token_seen_cumul_count,
                                );
                            }
                        }
                        origin_token_position += 1;
                    }
                    if p == 1 {
                        candidate_map.apply_pending_updates(function_lengths);
                        //apply updates for the first prefix scheme before estimating costs since it relies on min/max length
                    }
                    let verification_cost =
                        candidate_map.verification_cost_estimate(p, origin_word_count);
                    filter_cost_vector.push(filter_cost);
                    verification_cost_vector.push(verification_cost);
                    total_cost_vector.push(filter_cost + verification_cost);

                    if total_cost_vector[p] > total_cost_vector[p - 1] {
                        debug!("Best prefix scheme is {} with estimated total cost of {}, filter cost: {}, verification cost: {}. Moving on to verification phase.", p - 1, total_cost_vector[p - 1], filter_cost_vector[p - 1], verification_cost_vector[p - 1]);
                        debug!("The next prefix scheme {} has estimated total cost of {}, filter cost: {}, verification cost: {}.", p, total_cost_vector[p], filter_cost_vector[p], verification_cost_vector[p]);
                        verify_candidates(
                            path,
                            &origin_vectored_bow,
                            origin_token_position,
                            origin_cumulative_count,
                            &mut candidate_map,
                            &mut clone_map,
                            p - 1,
                            token_rankings,
                            threshold,
                            function_lengths,
                        )?;
                        break 'prefix_schemes;
                    } else {
                        //apply updates
                        candidate_map.apply_pending_updates(function_lengths);
                        if p == p_prefix {
                            debug!("Best prefix scheme is {} with estimated total cost of {}, filter cost: {}, verification cost: {}. This is the last prefix scheme, moving on to verification phase.", p, total_cost_vector[p], filter_cost_vector[p], verification_cost_vector[p]);
                            //return verify_candidates(candidate_map, path, function_code, p);
                            verify_candidates(
                                path,
                                &origin_vectored_bow,
                                origin_token_position,
                                origin_cumulative_count,
                                &mut candidate_map,
                                &mut clone_map,
                                p_prefix,
                                token_rankings,
                                threshold,
                                function_lengths,
                            )?;
                            break 'prefix_schemes;
                        }
                    }
                }
                debug!("Filter cost vector: {:?}", filter_cost_vector);
                debug!("Verification cost vector: {:?}", verification_cost_vector);
                debug!("Total cost vector: {:?}", total_cost_vector);
            }
            Ok(Err(_e)) => {
                warn!("File too large at path '{}', skipping.", path);
            }
            Err(_e) => {
                warn!("Failed to read file at path '{}', skipping.", path);
            }
        }
    }
    detection_progress.finish();
    Ok(clone_map)
}

fn verify_candidates<'a>(
    origin_function: &'a str,
    origin_vectored_bow: &Vec<(Word, usize)>,
    prefix_origin_last_token_seen_pos: usize,
    prefix_origin_last_token_seen_cumul_count: usize,
    candidate_map: &mut CandidateMap<'a>,
    clone_map: &mut CloneMap<'a>,
    p_prefix: usize,
    token_rankings: &HashMap<Word, usize>,
    threshold: f64,
    function_lengths: &HashMap<&'a str, usize>,
) -> Result<()> {
    // This function will take the candidate map for a function and verify the candidates that have enough matches
    // to be considered clones based on their full token vectors.
    // The clone_map is updated with the results, mapping original function ids to sets of clone function ids.
    let word_matcher: Matcher = Matcher::words_matcher();
    let origin_word_count = function_lengths.get(origin_function).copied().unwrap_or(0);
    debug!(
        "Verifying candidates for function at path '{}', with word count {}.",
        origin_function, origin_word_count
    );
    let origin_vectored_bow = origin_vectored_bow.to_owned();
    let origin_token_count = origin_vectored_bow.len();
    let candidates_to_verify = candidate_map.get_candidates_with_n_matches(p_prefix, "at_least"); // (token_position, cumulative_count)
    let origin_vector_readable: Vec<(String, usize)> = origin_vectored_bow
        .iter()
        .map(|(token, count)| (String::from_utf8_lossy(token).to_string(), *count))
        .collect();
    debug!("sorted origin vector: {:?}", origin_vector_readable);
    debug!("origin_function: {:?}", origin_function);
    for candidate in candidates_to_verify {
        debug!("----------------------");
        debug!("candidate_id as bytes: {:?}", candidate.as_bytes());
        if clone_map.contains_key(&candidate) {
            debug!(
                "SKIPPING candidate at path '{}' since it already has an entry in clone_map.",
                candidate
            );
            continue;
        }
        if candidate == origin_function {
            debug!(
                "Skipping self-comparison for function at path '{}'.",
                candidate
            );
            continue; //skip comparing the function to itself
        }
        let mut origin_last_token_seen_pos = prefix_origin_last_token_seen_pos;
        let mut origin_last_token_seen_cumul_count = prefix_origin_last_token_seen_cumul_count;
        let candidate_code = load_file(candidate, 1024 * 1024 * 1024)?
            .map_err(|e| anyhow::anyhow!("Error loading file '{}': {}.", candidate, e))?;

        // load function, sort tokens by global frequency, calculate similarity, if above threshold add to clone map
        let candidate_bow = word_matcher.bag_of_words(&candidate_code, true);
        let vectored_candidate_bow = candidate_bow.sort_by(token_rankings)?;
        let candidate_word_count = function_lengths.get(candidate).copied().unwrap();
        let candidate_token_count = vectored_candidate_bow.len();
        let current_threshold =
            (max(origin_word_count, candidate_word_count) as f64 * threshold).round() as usize;
        let (mut candidate_last_token_seen_pos, candidate_last_token_seen_cumul_count) =
            candidate_map.get_last_token_seen_pos(candidate);
        let mut new_matches = 0usize;
        let prefix_matches = candidate_map.get_token_matches(candidate);
        while origin_last_token_seen_pos < origin_token_count
            && candidate_last_token_seen_pos + 1 < candidate_token_count
        {
            let upper_bound = min(
                origin_word_count - origin_last_token_seen_cumul_count,
                candidate_word_count - candidate_last_token_seen_cumul_count,
            );
            let current_matches = prefix_matches + new_matches;
            let origin_token_tuple = &origin_vectored_bow[origin_last_token_seen_pos];
            let (candidate_token, candidate_token_count) =
                &vectored_candidate_bow[candidate_last_token_seen_pos + 1];

            let candidate_current_token_pos = candidate_last_token_seen_pos + 1;
            // let candidate_current_token_cumul_count =  candidate_last_token_seen_cumul_count + *candidate_token_count;

            debug!("Current threshold: {}", current_threshold);
            debug!(
                "Current matches: {} + {} = {}",
                prefix_matches, new_matches, current_matches
            );
            debug!("Upper bound of remaining matches: {}", upper_bound);

            let origin_rank = token_rankings
                .get(&origin_token_tuple.0)
                .copied()
                .unwrap_or(usize::MAX);
            let candidate_rank = token_rankings
                .get(candidate_token)
                .copied()
                .unwrap_or(usize::MAX);

            debug!(
                "Origin: {}, rank: {}, position: {} | Candidate: {}, rank: {}, position: {}",
                String::from_utf8_lossy(&origin_token_tuple.0),
                origin_rank,
                origin_last_token_seen_pos,
                String::from_utf8_lossy(candidate_token),
                candidate_rank,
                candidate_current_token_pos
            );

            if current_matches >= current_threshold {
                //already reached the threshold, we can stop comparing this candidate and add it to the clone map
                debug!(
                    "Threshold reached with current matches {}, adding to clone map.",
                    current_matches
                );
                break;
            } else if upper_bound + current_matches >= current_threshold {
                if origin_token_tuple.0 == *candidate_token {
                    //it's a match
                    debug!("MATCHING!");
                    new_matches += min(origin_token_tuple.1, *candidate_token_count);
                    candidate_last_token_seen_pos = candidate_current_token_pos;
                    origin_last_token_seen_pos += 1;
                    origin_last_token_seen_cumul_count += origin_token_tuple.1;
                } else if origin_rank > candidate_rank {
                    //origin token is more frequent than candidate token, so we move in the candidate vector
                    debug!("origin_count > candidate_count");
                    candidate_last_token_seen_pos = candidate_current_token_pos;
                } else {
                    //candidate token is more frequent than origin token, so we move in the origin vector
                    debug!("candidate_count > origin_count");
                    origin_last_token_seen_pos += 1;
                    origin_last_token_seen_cumul_count += *candidate_token_count;
                }
            } else {
                debug!("UPPER BOUND + current_matches is {}, which is not enough to reach the threshold of {}. Stopping comparison for this candidate.", upper_bound + current_matches, current_threshold);
                debug!(
                    "origin_last_token_seen_pos: {}, candidate_last_token_seen_pos: {}",
                    origin_last_token_seen_pos, candidate_last_token_seen_pos
                );
                break;
            }
        }
        candidate_map.add_candidate(
            candidate,
            function_lengths,
            new_matches,
            candidate_last_token_seen_pos,
            candidate_last_token_seen_cumul_count,
        );
        if candidate_map.get_token_matches(candidate) >= current_threshold {
            insert_clone_relation(clone_map, origin_function, candidate);
            debug!("*** CLONE DETECTED! ***");
            debug!(
                "Origin: {}, Candidate: {}, Similarity >= {:.2} %",
                origin_function,
                candidate,
                (candidate_map.get_token_matches(candidate) as f64
                    / max(origin_word_count, candidate_word_count) as f64)
                    * 100.0
            );
        }
        debug!("**********")
    }
    Ok(())
}

fn insert_clone_relation<'a>(
    clone_map: &mut CloneMap<'a>,
    origin_function: &'a str,
    candidate: &'a str,
) {
    let origin_entry = clone_map
        .entry(origin_function)
        .or_insert_with(|| Either::Left(HashSet::new()));

    // Origin must always store the set of its clones as Left(HashSet<_>).
    if let Either::Left(clones) = origin_entry {
        clones.insert(candidate);
    } else {
        *origin_entry = Either::Left(HashSet::from([candidate]));
    }

    // Clone points back to its origin as Right(origin_hash).
    clone_map.insert(candidate, Either::Right(origin_function));
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_prefix_length() {
        use rand::{Rng, SeedableRng};
        let mut rng = rand::rngs::StdRng::seed_from_u64(0);

        for _ in 0..10_000 {
            let word_count: usize = rng.gen_range(1..=10_000);
            // threshold=0 is the known exception: ceil(0)=0 gives word_count+1
            let threshold: f64 = rng.gen_range(f64::MIN_POSITIVE..=1.0);

            let result = prefix_length(word_count, threshold);
            assert!(
                result >= 1,
                "prefix_length({word_count}, {threshold}) = {result} is not >= 1"
            );
            assert!(
                result <= word_count,
                "prefix_length({word_count}, {threshold}) = {result} exceeds word_count"
            );
        }

        // threshold=0 produces word_count+1, violating the upper bound
        for word_count in [1usize, 2, 10, 100] {
            assert_eq!(prefix_length(word_count, 0.0), word_count + 1);
        }
    }
}
